<?php

namespace App\Services;

use TCPDF;
use Carbon\Carbon;

class LeavePdfService
{
    public function generateLeaveReport($employee, $leaveRecords)
    {
        // Create a new PDF document
        $pdf = new TCPDF();

        // Remove the default header
        $pdf->setPrintHeader(false);

        // Set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Arrogance Technologies Pvt Ltd');
        $pdf->SetTitle('Leave Report');
        $pdf->SetSubject('Leave Report');

        // Set header and footer fonts
        $pdf->setFooterFont(['helvetica', '', 10]);

        // Set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // Set margins
        $pdf->SetMargins(PDF_MARGIN_LEFT, 50, PDF_MARGIN_RIGHT);
        $pdf->SetHeaderMargin(10);
        $pdf->SetFooterMargin(10);

        // Set auto page breaks
        $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

        // Set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

        // Add a page
        $pdf->AddPage();

        // Set font
        $pdf->SetFont('helvetica', '', 12);

        // Add company logo and information
        $logo = public_path('images/logo-jpg.jpg');
        $pdf->Image($logo, 35, 10, 50, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        $pdf->SetY(15);
        $pdf->SetX(85);
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->Cell(0, 5, 'Arrogance Technologies Pvt Ltd', 0, 1, 'L');
        $pdf->SetFont('helvetica', '', 10);
        $pdf->SetY(25); // Adjust Y position to align properly
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 5, '14/6, Park Street, Colombo 02, Sri Lanka', 0, 1, 'L');
        $pdf->Cell(0, 5, 'Web: www.arrogance.lk', 0, 1, 'L');
        $pdf->Cell(0, 5, 'Phone: +94113416500', 0, 1, 'L');
        
        // Draw a line under the header
        $pdf->Line(15, 40, 195, 40);

        // Employee Details and Photo
        if ($employee->profile_photo_path) {
            $photo = storage_path('app/public/' . $employee->profile_photo_path);
            $pdf->Image($photo, 165, 45, 30, 30, '', '', 'T', false, 300, '', false, false, 0, false, false, false);
        } else {
            $initials = strtoupper(substr($employee->name, 0, 1));
            $pdf->SetXY(165, 45);
            $pdf->SetFont('helvetica', 'B', 20);
            $pdf->Cell(30, 30, $initials, 1, 0, 'C', 0, '', 0, false, 'T', 'C');
        }

        $pdf->SetY(50);
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 5, 'Employee Name: ' . $employee->name, 0, 1, 'L');
        $pdf->Cell(0, 5, 'Employee ID: ' . $employee->emp_no, 0, 1, 'L');

        // Move to next line
        $pdf->Ln(10);

        // Report header
        $pdf->SetFont('helvetica', 'B', 12);
        $pdf->Cell(0, 7, 'Leave Report', 0, 1, 'C');

        // Table header
        $pdf->SetFont('helvetica', 'B', 12);
        $pdf->SetFillColor(220, 220, 220);
        $pdf->Cell(40, 10, 'Start Date', 1, 0, 'C', 1);
        $pdf->Cell(40, 10, 'End Date', 1, 0, 'C', 1);
        $pdf->Cell(40, 10, 'Leave Type', 1, 0, 'C', 1);
        $pdf->Cell(60, 10, 'Reason', 1, 1, 'C', 1);

        // Table body
        $pdf->SetFont('helvetica', '', 10);
        foreach ($leaveRecords as $record) {
            $pdf->Cell(40, 10, Carbon::parse($record->start_date)->format('Y-m-d'), 1, 0, 'C');
            $pdf->Cell(40, 10, Carbon::parse($record->end_date)->format('Y-m-d'), 1, 0, 'C');
            $pdf->Cell(40, 10, $record->leave_type, 1, 0, 'C'); // Output for leave_type

            // Use MultiCell for wrapping text in the Reason column
            $pdf->MultiCell(60, 10, $record->reason, 1, 'C', 0, 1);
        }

        // Footer with generation details
        $pdf->Ln(10);
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 5, 'Report generated by: ' . auth()->user()->name, 0, 1, 'L');
        $pdf->Cell(0, 5, 'Date: ' . Carbon::now('Asia/Colombo')->format('Y-m-d'), 0, 1, 'L');
        $pdf->Cell(0, 5, 'Time: ' . Carbon::now('Asia/Colombo')->format('H:i'), 0, 1, 'L');

        // Output the PDF
        $pdf->Output("{$employee->emp_no}_{$employee->name}_leave_report.pdf", 'I');
    }
}
